### ISSUE TITLE
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by sangarajukumar** [ExplainableML/czsl#23]
when I run the vesicular_gru.py here is the error:

`/home/kumar/anaconda3/envs/pytorch/bin/python /home/kumar/SKKU/khanhlee/vesicular-gru/vesicular-gru-master/vesicular_gru.py 
positive:  1771
negative:  6058
Length Train Dataset:  7829 

positive:  443
negative:  1515
Length Validation Dataset:  1958 

/home/kumar/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/rnn.py:62: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.01 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "
Traceback (most recent call last):
  File "/home/kumar/SKKU/khanhlee/vesicular-gru/vesicular-gru-master/vesicular_gru.py", line 457, in <module>
    train()
  File "/home/kumar/SKKU/khanhlee/vesicular-gru/vesicular-gru-master/vesicular_gru.py", line 406, in train
    epoch_loss_train_avg = train_one_epoch(learning_rate)
  File "/home/kumar/SKKU/khanhlee/vesicular-gru/vesicular-gru-master/vesicular_gru.py", line 182, in train_one_epoch
    for i, data in enumerate(train_loader, 0):
  File "/home/kumar/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/kumar/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/kumar/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/kumar/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/kumar/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/kumar/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kumar/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kumar/SKKU/khanhlee/vesicular-gru/vesicular-gru-master/vesicular_gru.py", line 74, in __getitem__
    lines = load_text_file(self.lst_path[index])
  File "/home/kumar/SKKU/khanhlee/vesicular-gru/vesicular-gru-master/vesicular_gru.py", line 43, in load_text_file
    with open(file_text) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/pssm/pssm/membrane/cv/P33450.pssm'

Process finished with exit code 1
`
I have no idea how to fix this error. p33450.pssm is really an existing file in the directory: 'data/pssm/pssm/membrane/cv/P33450.pssm'. How can I fix that error

**Comment by mancinimassimiliano** [comment]
Hello @sangarajukumar! I guess you refer to this repo, right? https://github.com/khanhlee/vesicular-gru. I/we are not authors of that code, so it is better if you open an issue directly there.
